ClothBazar.Web/Controllers/CategoryController.cs
using ClothBazar.Entities;
using ClothBazar.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.Web.Controllers
{
    public class CategoryController : Controller
    {
        categoriesService categoryService = new categoriesService();
        
        [HttpGet]
        public ActionResult Index()
        {
            var categories = categoryService.GetCategories();

            return View(categories);
        } 

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Category category)
        {
            categoryService.SaveCategory(category);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var category = categoryService.GetCategory(Id);
            return View(category);
        }

        [HttpPost]
        public ActionResult Edit(Category category)
        {
            categoryService.UpdateCategory(category);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(int Id)
        {
            var category = categoryService.GetCategory(Id);
            return View(category);
        }

        [HttpPost]
        public ActionResult Delete(Category category)
        {
            categoryService.DeleteCategory(category.Id);
            return RedirectToAction("Index");
        }

    }
}

ClothBazar.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.Web.Controllers
{
    public class SharedController : Controller
    {
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0];

                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);

                var path = Path.Combine(Server.MapPath("~/content/images/"), fileName);

                file.SaveAs(path);

                result.Data = new { Success = true, ImageURL = string.Format("/content/images/{0}", fileName) };

                //var newImage = new Image() { Name = fileName };

                //if (ImagesService.Instance.SaveNewImage(newImage))
                //{
                //    result.Data = new { Success = true, Image = fileName, File = newImage.ID, ImageURL = string.Format("{0}{1}", Variables.ImageFolderPath, fileName) };
                //}
                //else
                //{
                //    result.Data = new { success = false, Message = new HttpStatusCodeResult(500) };
                //}
            }
            catch (Exception ex)
            {
                result.Data = new { Success = false, Message = ex.Message };
            }

            return result;
        }
    }
}

ClothBazar.Web/Views/Category/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create Catagory</h2>
<form method="post">
    <label>Name</label>
    <input type="text" name="Name" style="width:auto;" />
    <br />
    <label>Description</label>
    <input type="text" name="Description" style="width:auto;">
    <br />
    <label>Image</label>
    <input type="hidden" id="ImageURL" name="ImageURL" />
    <input id="imageUpload" type="file" name="Image" accept=".png, .jpg, .jpeg">
    <div class="col-md-4">
        <div class="thumb">
            @*<img class="img-thumbnail img-fluid" id="categoryImage" src="@imageURL" />*@
            <img id="categoryImage" />
        </div>
    </div>
    <br />
    <button type="submit">Save</button>
</form>

<script>
    $("#imageUpload").change(function () {
		var element = this;

		var formData = new FormData();

		var totalFiles = element.files.length;

		for (var i = 0; i < totalFiles; i++) {
			var file = element.files[i];
			formData.append("Photo", file);
        } 
        $.ajax({
			type: 'POST',
			url: '@Url.Action("UploadImage", "Shared")',
			dataType: 'json',
			data: formData,
			contentType: false,
			processData: false
		})
        .done(function (response) {
        	console.log(response);

        	if(response.Success)
        	{
        		$("#ImageURL").val(response.ImageURL);
        		$("#categoryImage").attr("src", response.ImageURL);
        	}
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
    });
</script>

ClothBazar.Web/Views/Category/Delete.cshtml
@*@Model ClothBazar.Entities.Category*@
@{
    ViewBag.Title = "Delete";
}

<h2>Delete Catagory</h2>
<h3>Are you Sure!Want to Delete?</h3>
<form method="post">
    <input type="hidden" name="Id" value="@Model.Id" />
    <button type="submit">Yes Delete</button>
</form>
<a href="/Index" >Cancel</a>

ClothBazar.Web/Views/Category/Edit.cshtml
@*@Model ClothBazar.Entities.Category*@
@{
    ViewBag.Title = "Edit";
}

    <h2>Edit Catagory</h2>
    <form method="post">
        <input type="hidden" name="Id" value="@Model.Id" />

        <label>Name</label>
        <input type="text" name="Name" value="@Model.Name" />
        <br /><hr />

        <label>Description</label>
        <input type="text" name="Description" value="@Model.Description">
        <br /><hr />
        <button type="submit">Save</button>
    </form>

ClothBazar.Web/Views/Category/Index.cshtml
@model List<ClothBazar.Entities.Category>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@foreach(var category in Model)
{
    <h3>@category.Name</h3>
}